services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8080/actuator/health || curl -fsS http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 15
      start_period: 5s
